---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: default
  labels:
    app: app1
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6000
  selector:
    app: app1
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: default
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      volumes:
        - name: pv-app
          persistentVolumeClaim:
            claimName: k8s-pvc
      containers:
        - name: webapp1
          image: us-central1-docker.pkg.dev/csci-5409-s23-k8s/web1/webapp1:latest
          ports: 
            - containerPort: 6000
          volumeMounts:
            - name: pv-app
              mountPath: /jiaye_PV_dir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi