# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: computeandstorage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63omputeandstorage.proto\x12\x11\x63omputeandstorage\"\x1c\n\x0cStoreRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1b\n\nStoreReply\x12\r\n\x05s3uri\x18\x01 \x01(\t\"\x1d\n\rAppendRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\r\n\x0b\x41ppendReply\"\x1e\n\rDeleteRequest\x12\r\n\x05s3uri\x18\x01 \x01(\t\"\r\n\x0b\x44\x65leteReply2\x82\x02\n\rEC2Operations\x12M\n\tStoreData\x12\x1f.computeandstorage.StoreRequest\x1a\x1d.computeandstorage.StoreReply\"\x00\x12P\n\nAppendData\x12 .computeandstorage.AppendRequest\x1a\x1e.computeandstorage.AppendReply\"\x00\x12P\n\nDeleteFile\x12 .computeandstorage.DeleteRequest\x1a\x1e.computeandstorage.DeleteReply\"\x00\x62\x06proto3')



_STOREREQUEST = DESCRIPTOR.message_types_by_name['StoreRequest']
_STOREREPLY = DESCRIPTOR.message_types_by_name['StoreReply']
_APPENDREQUEST = DESCRIPTOR.message_types_by_name['AppendRequest']
_APPENDREPLY = DESCRIPTOR.message_types_by_name['AppendReply']
_DELETEREQUEST = DESCRIPTOR.message_types_by_name['DeleteRequest']
_DELETEREPLY = DESCRIPTOR.message_types_by_name['DeleteReply']
StoreRequest = _reflection.GeneratedProtocolMessageType('StoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOREREQUEST,
  '__module__' : 'computeandstorage_pb2'
  # @@protoc_insertion_point(class_scope:computeandstorage.StoreRequest)
  })
_sym_db.RegisterMessage(StoreRequest)

StoreReply = _reflection.GeneratedProtocolMessageType('StoreReply', (_message.Message,), {
  'DESCRIPTOR' : _STOREREPLY,
  '__module__' : 'computeandstorage_pb2'
  # @@protoc_insertion_point(class_scope:computeandstorage.StoreReply)
  })
_sym_db.RegisterMessage(StoreReply)

AppendRequest = _reflection.GeneratedProtocolMessageType('AppendRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPENDREQUEST,
  '__module__' : 'computeandstorage_pb2'
  # @@protoc_insertion_point(class_scope:computeandstorage.AppendRequest)
  })
_sym_db.RegisterMessage(AppendRequest)

AppendReply = _reflection.GeneratedProtocolMessageType('AppendReply', (_message.Message,), {
  'DESCRIPTOR' : _APPENDREPLY,
  '__module__' : 'computeandstorage_pb2'
  # @@protoc_insertion_point(class_scope:computeandstorage.AppendReply)
  })
_sym_db.RegisterMessage(AppendReply)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'computeandstorage_pb2'
  # @@protoc_insertion_point(class_scope:computeandstorage.DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)

DeleteReply = _reflection.GeneratedProtocolMessageType('DeleteReply', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREPLY,
  '__module__' : 'computeandstorage_pb2'
  # @@protoc_insertion_point(class_scope:computeandstorage.DeleteReply)
  })
_sym_db.RegisterMessage(DeleteReply)

_EC2OPERATIONS = DESCRIPTOR.services_by_name['EC2Operations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOREREQUEST._serialized_start=46
  _STOREREQUEST._serialized_end=74
  _STOREREPLY._serialized_start=76
  _STOREREPLY._serialized_end=103
  _APPENDREQUEST._serialized_start=105
  _APPENDREQUEST._serialized_end=134
  _APPENDREPLY._serialized_start=136
  _APPENDREPLY._serialized_end=149
  _DELETEREQUEST._serialized_start=151
  _DELETEREQUEST._serialized_end=181
  _DELETEREPLY._serialized_start=183
  _DELETEREPLY._serialized_end=196
  _EC2OPERATIONS._serialized_start=199
  _EC2OPERATIONS._serialized_end=457
# @@protoc_insertion_point(module_scope)
